---
# file: roles/dvd/tasks/main.yml

#- name: preconfigure libdvd-pkg
#  shell: |
#    echo 'libdvd-pkg libdvd-pkg/post-invoke_hook-install boolean true' | debconf-set-selections
#    echo 'libdvd-pkg libdvd-pkg/build boolean true' | debconf-set-selections

- name: apt | install libdvd-pkg
  apt:
    name: libdvd-pkg
    state: present
    install_recommends: no

- name: reconfigure libdvd-pkg
  dpkg_reconfigure:
    pkg: libdvd-pkg
    answers: |
     libdvd-pkg/post-invoke_hook-install: boolean true
     libdvd-pkg/build: boolean true

- name: change udev rule to allow KODI to eject optical disks
  block:
    - name: read udev rule for cdrom_id.rules
      slurp:
        src: /lib/udev/rules.d/60-cdrom_id.rules
      register:
        cdrom_udev_rule
    
    - name: write modified udev rule for cdrom_id.rules
      copy:
        content: |
          {{ cdrom_udev_rule.content | b64decode | regex_replace('--lock-media ', '') }}
        dest: /etc/udev/rules.d/60-cdrom_id.rules
