---

- name: apt | install pulseaudio, pavucontrol and vdr-plugin-pulsecontrol
  apt:
    name:
      - alsa-base
      - alsa-utils
      - pulseaudio
      - pavucontrol
      - vdr-plugin-pulsecontrol
      - python3-pulsectl
      - python3-dasbus
    state: present
    install_recommends: no

- name: create /etc/asound.conf with pulseaudio as default device
  template:
    src: templates/alsa/asound.conf.j2
    dest: /etc/asound.conf

- name: "create /etc/dbus-1/system.d/org.yavdr.dbus_pulse_ctl.conf to configure access to dbus_pulsectl"
  template:
    src: "dbus_pulsectl/org.yavdr.dbus_pulsectl.conf.j2"
    dest: "/etc/dbus-1/system.d/org.yavdr.dbus_pulse_ctl.conf"

- name: ensure ~/bin exists for vdr user
  file:
    path: "{{ vdr.home }}/bin"
    state: directory
    mode: 0755

- name: create dbus_pulsectl script
  template:
    src: "dbus_pulsectl/dbus_pulsectl.py.j2"
    dest: "{{ vdr.home }}/bin/dbus_pulsectl"
    mode: 0755

- name: ensure ~/.config/systemd/user exists for vdr user
  file:
    path: "{{ vdr.home }}/.config/systemd/user"
    state: directory
    mode: 0755

- name: create dbus service for dbus_pulsectl
  template:
    src: dbus_pulsectl/dbus-pulsectl.service.j2
    dest: "{{ vdr.home }}/.config/systemd/user/dbus-pulsectl.service"
    owner: "{{ vdr.user }}"

    # TODO: better way to enable unit than in openbox autostart set by yavdr-desktop?
