xorg_services:
  - service_name: 'yavdr-xorg.servie'
    instance_name: 'yavdr-xorg.service'
    notification: 'Start yavdr-xorg'

  - service_name: 'xlogin@.service'
    instance_name: 'xlogin@{{ vdr.user | default("vdr") }}.service'
    notification: 'Start xlogin'

  - service_name: 'x@.service'
    instance_name: 'x@vt7.service'
