- name: create osd2web.service for the session
  template:
    src: templates/systemd/user/osd2web.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/osd2web.service'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    mode: 0644
