---
- name: apt | install vdr-plugin-osd2web
  apt:
    name: vdr-plugin-osd2web
    state: present

- name: expand osd2web.service from template for the session
  template:
    src: templates/systemd/user/osd2web.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/osd2web.service'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'
    mode: 0644

- name: activate and start systemd unit osd2web.service
  systemd:
    name: osd2web.service
    state: running
    daemon_reload: yes
    masked: no
    enabled: yes
  become: yes
  become_user: "{{ vdr.user }}"
