---
# this playbook sets up network services for a yaVDR installation

- name: apt | install packages for network services
  apt:
      name:
          - avahi-daemon
          - avahi-utils
          #- biosdevname # caution: this may change device names after a minimal installation!
          - ethtool
          - nfs-common
          - vdr-addon-avahi-linker
          - wakeonlan
      state: present
      install_recommends: no

# Does this really work? We need a way to check if an interface supports WOL - Python Skript?
# - name: check WOL capabilities of network interfaces
#   shell: 'ethtool {{ item }} | grep -Po "(?<=Supports\sWake-on:\s).*$"'
#   register: wol
#   with_items: '{% for interface in ansible_interfaces if interface != 'lo' and interface != 'bond0' %}'

- name: restart autofs if running
  systemd:
    name: autofs
    state: restarted
    enabled: yes
    masked: no

- name: ensure autofs is running
  systemd:
    name: autofs
    state: started
    enabled: yes
    masked: no

- name: set video directory for avahi-linker
  ini_file:
    path: /etc/avahi-linker/default.cfg
    section: "targetdirs"
    option: "vdr"
    value: "{{ vdr.recdir }}"

- name: set vdr instance id for avahi-linker
  ini_file:
    path: /etc/avahi-linker/default.cfg
    section: "options"
    option: "vdr_instance_id"
    value: "{{ vdr.instance_id | default(0) }}"

- name: restart avahi-linker if running
  systemd:
    name: avahi-linker
    state: restarted
    enabled: yes
    masked: no

- name: ensure avahi-linker is started
  systemd:
    name: avahi-linker
    state: started
    enabled: yes
    masked: no

- name: ensure additional services for avahi-linker are active
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
    masked: no
  loop:
    - vdr-net-monitor
    - vdr-update-monitor
    - prevent-umount-on-pause
