---
# file roles/autoinstall-dvb-firmware/tasks/main.yml

- name: install LibreElec dvb-firmware files
  block:
    - name: clone git repository
      git:
        repo: "https://github.com/LibreElec/dvb-firmware.git"
        dest: /var/cache/dvb-firmware
        clone: yes
        update: yes
        depth: 1
        force: true

    - name: get firmware files to copy
      command: |
        find /var/cache/dvb-firmware/firmware  -type f -regex '.*/*\.\(fw\|bin\)$' -printf '%P\n'
      register: firmware_to_copy
      changed_when: false


    - name: create directories for firmware files
      file:
        state: directory
        path: "/var/cache/dvb-firmware/firmware/{{ item }}"
      loop: "{{ firmware_to_copy.stdout_lines | map('dirname') | unique | list }}"

    - name: copy firmware files to /lib/firmware
      copy:
        src: "/var/cache/dvb-firmware/firmware/{{ item }}"
        dest: /lib/firmware/
        owner: root
        group: root
        mode: "0644"
      loop: "{{ firmware_to_copy.stdout_lines }}"
