preferred_outputs:
  - HDMI
  - DP
  - DVI
  - VGA
  - TV
preferred_resolutions:
  - 7680x4320
  - 3840x2160
  - 1920x1080
  - 1280x720
  - 720x576
preferred_refreshrates:
  - 50
  - 60

intel_boot_options: ""
intel_set_boot_edid: false
intel_driver: "intel"  # choose one of "intel" and "modesetting"
softhddevice_intel_output_method: "va-api"  # choose one of va-api, va-api-glx, va-api-egl
nvidia_force_dpi: 0

yavdr_frontend:
    attach_on_startup: auto  # choose one of auto, always or never
