- name: apt | install dependencies
  apt:
    name:
      - git
      - python3-lxml
    state: present

- name: copy channel_linker script
  template:
    src: roles/channellogos/templates/channel_linker.py.j2
    dest: /usr/local/bin/channel_linker
    mode: 0755

- name: get current mediaportal channel logos
  git:
    repo: "https://github.com/Jasmeet181/mediaportal-{{ item }}-logos.git"
    dest: "/usr/local/lib/mediaportal-{{ item }}-logos"
    clone: yes
    depth: 1
    update: yes
  loop: "{{ channellogo_languages }}"

- name: update channel logo links
  command: /usr/local/bin/channel_linker {{ channellogo_languages | map('quote') | join(' ') }}
