- name: create kodi.service for the user session
  template:
      src: 'templates/kodi.service.j2'
      dest: '{{ vdr.home }}/.config/systemd/user/kodi.service'
      mode: 0644
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'

- name: create kodi user directory
  file:
      dest: '{{ kodi_config_dir }}/userdata/keymaps'
      state: directory
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0775"
      recurse: yes

- name: copy Lircmap.xml if it does not exist yet
  copy:
      dest: '{{ kodi_config_dir }}/userdata/Lircmap.xml'
      src: 'files/userdata/Lircmap.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: no

- name: copy remote.xml if it does not exist yet
  copy:
      dest: '{{ kodi_config_dir }}/userdata/keymaps/remote.xml'
      src: 'files/userdata/keymaps/remote.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: no

- name: expand template for set-kodi-display
  template:
    src: 'templates/set-kodi-display.j2'
    dest: '/usr/bin/set-kodi-display'
    mode: "0755"
