---
- name: create kodi.service for the user session
  template:
      src: 'templates/kodi.service.j2'
      dest: '{{ vdr.home }}/.config/systemd/user/kodi.service'
      mode: 0644
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'

- name: create kodi user directory
  file:
      dest: '{{ kodi_config_dir }}/userdata/keymaps'
      state: directory
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0775"
      recurse: true

- name: copy Lircmap.xml if it does not exist yet
  copy:
      dest: '{{ kodi_config_dir }}/userdata/Lircmap.xml'
      src: 'files/userdata/Lircmap.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: false

- name: copy remote.xml if it does not exist yet
  copy:
      dest: '{{ kodi_config_dir }}/userdata/keymaps/remote.xml'
      src: 'files/userdata/keymaps/remote.xml'
      owner: '{{ vdr.user }}'
      group: '{{ vdr.group }}'
      mode: "0664"
      force: false

- name: expand template for set-kodi-display
  template:
      src: 'templates/set-kodi-display.j2'
      dest: '/usr/bin/set-kodi-display'
      mode: "0755"

- name: set flatpak permissions for kodi to access media directories
  block:
      - name: get output for current permissions
        command: /usr/bin/flatpak --user override --show tv.kodi.Kodi
        become_user: vdr
        register: kodi_permissions_output
        changed_when: false

      - name: determine folders to add to the kodi flatpak configuration
        set_fact:
            kodi_permissions_to_add: |
             {{ flatpak_kodi_allowed_dirs | difference(
                   (
                     kodi_permissions_output.stdout_lines |
                     select('match', '^filesystems=') |
                     first | default([]) |
                     regex_search('(?<=filesystems=).*') | default('', true)
                   ).split(';') | select() | default([])) | list
             }}

      - name: set kodi flatpak directory access permissions
        command: '/usr/bin/flatpak --user override --filesystem="{{ item }}" tv.kodi.Kodi'
        become_user: vdr
        loop: "{{ kodi_permissions_to_add }}"
        when: kodi_permissions_to_add | length > 0
  when: kodi_as_flatpak
