---

- name: Install kodi as flatpak
  block:
    - name: ensure flatpak is installed
      apt:
        name: flatpak
        state: present
    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: flatpak | install kodi packages
      flatpak:
        name: "tv.kodi.Kodi"
        state: present
        remote: flathub
  
    - name: Upgrade all flatpaks
      command: flatpak update --noninteractive
      register: flatpak_update_output
      changed_when: "'app/' in flatpak_update_output.stdout"

    - name: remove unused flatpaks
      command: flatpak uninstall --unused --noninteractive
      register: flatpak_uninstall_output
      changed_when: "'Uninstalling' in flatpak_uninstall_output.stdout"

    - name: check if the nvidia version matches if the module has been loaded
      shell: |
       test -f /proc/driver/nvidia/version || exit 0
       installed_version=$(grep -m1 -Po '\d+\.\d+' /proc/driver/nvidia/version)
       version_part=$(sed 's/\./-/g' <<< "$installed_version")
       grep -q "^nvidia-${version_part}" < <(flatpak list) && exit 0 || exit 1
      register:  flatpak_nvidia_mismatch
      failed_when: flatpak_nvidia_mismatch.rc > 1
      changed_when: flatpak_nvidia_mismatch.rc == 1
      notify: "rerun required"
  when: kodi_as_flatpak


- name: Install kodi as debian package
  block:
  - name: apt | install kodi packages
    apt:
      name:
        - kodi
        - kodi-pvr-vdr-vnsi
        - python3-lxml
      state: present
      install_recommends: no
  
  - name: apt | install kodi-send (team-xbmc PPA)
    apt:
      name: "kodi-eventclients-kodi-send"
      state: present
      install_recommends: no
    register: team_xbmc_ppa
    ignore_errors: True
  
  - name: apt | install kodi-send (fallback)
    apt:
      name: "kodi-eventclients-xbmc-send" # fallback to old xbmc-send package
      state: present
      install_recommends: no
    when: team_xbmc_ppa.failed
  when: not kodi_as_flatpak
