---

- name: custom grub configuration for timeout and reboot halt
  template:
    src: templates/50_custom.j2
    dest: /etc/grub.d/50_custom
    mode: '0775'
  notify: [ 'Update GRUB' ]

# TODO: add special case if plymouth is used
- name: let the system boot quietly
  lineinfile:
      dest: /etc/default/grub
      state: present
      regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=")'
      line: '\1{{ grub.boot_options }} {{ intel_boot_options }}"'
      backrefs: yes
  notify: [ 'Update GRUB' ]

- name: set GRUB_TIMEOUT
  lineinfile:
      dest: /etc/default/grub
      state: present
      regexp: '^(GRUB_TIMEOUT=)'
      line: 'GRUB_TIMEOUT={{ grub.timeout }}'
      backrefs: yes
  notify: [ 'Update GRUB' ]

- name: set GRUB_TIMEOUT_STYLE
  lineinfile:
      dest: /etc/default/grub
      state: present
      regexp: '^(GRUB_TIMEOUT_STYLE=)'
      line: '\1{{ "hidden" if grub.timeout == 0 else "menu" }}'
      backrefs: yes
  notify: [ 'Update GRUB' ]
