- name: install udiskie
  apt:
    name:
      - policykit-1
      - udiskie
    state: present

- name: create ~/.config/udiskie
  file:
    name: '{{ vdr.home }}/.config/udiskie'
    state: directory
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: expand template for udiskie's config.yml
  template:
    src: templates/config.yml.j2
    dest: '{{ vdr.home }}/.config/udiskie/config.yml'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'


- name: create ~/.config/systemd/user
  file:
    name: '{{ vdr.home }}/.config/systemd/user'
    state: directory
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: expand template for udiskie's systemd unit
  template:
    src: templates/udiskie.service.j2
    dest: '{{ vdr.home }}/.config/systemd/user/udiskie.service'
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: create ~/bin
  file:
    name: '{{ vdr.home }}/bin'
    state: directory
    owner: '{{ vdr.user }}'
    group: '{{ vdr.group }}'

- name: expand template for mount helper script
  template:
    src: templates/udiskie_vdr_mount_helper.j2
    dest: '{{ vdr.home }}/bin/udiskie_vdr_mount_helper'
    mode: 0755
    owner: "{{ vdr.user }}"
    group: "{{ vdr.group }}"

- name: expand template for udiskie vdr commands
  template:
    src: templates/umount_all.j2
    dest: /usr/share/vdr/command-hooks/commands.udiskie.conf
